## 1

In [6]:
l1 = []
for i in range(10):
    if i%2==0:
        l1.append(i)

l2 = []
for i in range(5):
    l2.append(i**2)

l3 = []
i = 0
while i<15:
    l3.append(i)
    i += 3

l1, l2, l3


([0, 2, 4, 6, 8], [0, 1, 4, 9, 16], [0, 3, 6, 9, 12])

In [7]:
l1 = [i for i in range(10) if i%2==0]

l2 = [i**2 for i in range(5)]

l3 = [i for i in range(0,15,3)]

l1, l2, l3

([0, 2, 4, 6, 8], [0, 1, 4, 9, 16], [0, 3, 6, 9, 12])

## 2

In [40]:
import numpy as np

In [44]:
a = np.array([2,3,5,7])

len(a), a.size

(4, 4)

Tipo di dato = int32

In [10]:
a.dtype

dtype('int32')

In [43]:
def primo(i):
    if i==0 or i == 1:
        return 1
    if i>3:
        for n in range(2, int(i/2)+1):
            if i%n==0:
                return 1
    return 0

a = np.array([i for i in range(10) if primo(i)==0])
a

array([2, 3, 5, 7])

## 3

In [31]:
a = np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [32]:
b = a[1:4]
b

array([ 4,  7, 10])

In [33]:
c = a[::-1]
c

array([19, 16, 13, 10,  7,  4,  1])

In [34]:
a / c

array([ 0.05263158,  0.25      ,  0.53846154,  1.        ,  1.85714286,
        4.        , 19.        ])

In [35]:
lista_a = list(range(1,20,3))
lista_a

[1, 4, 7, 10, 13, 16, 19]

In [36]:
lista_b = lista_a[1:4]
lista_b

[4, 7, 10]

In [37]:
lista_c = lista_a[::-1]
lista_c

[19, 16, 13, 10, 7, 4, 1]

In [38]:
lista_d = []

for i in range(len(lista_a)):
    d = lista_a[i] / lista_c[i]
    lista_d.append(d)

lista_d

[0.05263157894736842,
 0.25,
 0.5384615384615384,
 1.0,
 1.8571428571428572,
 4.0,
 19.0]