## 1

In [2]:
import numpy as np

In [3]:
a = np.array([2,3,5,7,11,13,17,19])

a[a > 10]

array([11, 13, 17, 19])

In [4]:
a[a%2==0]

array([2])

## 2

In [11]:
a = np.arange(0,12).reshape((4,3))

b = a[1::2, :]

c = a[2, :]

a, b, c

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11]]),
 array([6, 7, 8]))

In [13]:
a/c

array([[0.        , 0.14285714, 0.25      ],
       [0.5       , 0.57142857, 0.625     ],
       [1.        , 1.        , 1.        ],
       [1.5       , 1.42857143, 1.375     ]])

## 3

In [15]:
import random 

In [17]:
a = np.array([np.random.uniform(0,1,30)]).reshape((10,3))
a

array([[0.83757477, 0.28077951, 0.9086121 ],
       [0.02953419, 0.16604598, 0.94569554],
       [0.74693994, 0.63664268, 0.880965  ],
       [0.21274644, 0.71144148, 0.2295097 ],
       [0.06807038, 0.69348164, 0.20574715],
       [0.13183597, 0.06098646, 0.90107137],
       [0.53796034, 0.29147996, 0.8489611 ],
       [0.84861336, 0.56057828, 0.77131144],
       [0.50826308, 0.95869614, 0.38882958],
       [0.56175015, 0.14535648, 0.83023906]])

In [20]:
dist = np.abs(a-0.5)

indici = np.argmin(dist, axis=1)

vicini = a[np.arange(a.shape[0]),indici]

vicini

array([0.28077951, 0.16604598, 0.63664268, 0.71144148, 0.69348164,
       0.13183597, 0.53796034, 0.56057828, 0.50826308, 0.56175015])

## 4

In [22]:
a = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 
              162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
a.min()

60

In [23]:
a.max()

164

In [25]:
b = a>120

perc = np.mean(b) * 100
perc

52.38095238095239

## 5

In [21]:
a = np.array([50000, 105250, 55000, 89000])

tot_1 = a.sum()
tot_1

299250

In [22]:
a = np.array([i*1.15 if i==105250 else i for i in a])
a

array([ 50000. , 121037.5,  55000. ,  89000. ])

In [23]:
a = np.array([i*1.2 if i==50000 else i for i in a])
a

array([ 60000. , 121037.5,  55000. ,  89000. ])

In [24]:
a = np.array([i*1.1 if i==55000 or i==89000 else i for i in a])
a

array([ 60000. , 121037.5,  60500. ,  97900. ])

In [25]:
tot_2 = a.sum()
tot_2

339437.5

In [26]:
cost = tot_2 - tot_1

print('Costo totale:', cost)

Costo totale: 40187.5


## 6

In [35]:
em = np.loadtxt('./emissioni.txt', dtype=float)
em

array([ 6.01,  7.73,  8.63, 16.5 , 14.61,  4.55, 10.8 , 17.43,  4.18,
       11.66,  4.75,  9.23, 12.66,  5.4 , 12.44, 18.4 ,  4.23, 17.2 ,
       13.92, 13.76, 14.84,  9.5 , 14.25, 14.95, 16.19, 10.82, 14.04,
        6.79, 15.17,  6.41,  6.88, 15.11,  7.07,  7.56, 19.78,  8.42,
       14.95, 17.88, 14.16, 13.95, 11.  , 10.25,  6.4 , 16.89, 10.93,
       11.7 , 16.82, 19.93, 10.36,  7.79, 13.72,  5.4 , 18.19, 14.52,
        9.78,  5.85,  4.24, 11.91,  9.72,  8.37, 11.83, 19.17, 16.05,
       12.79, 14.95,  4.79, 10.81, 16.57, 17.88, 19.32,  8.15, 13.  ,
       19.29,  6.03,  5.77,  6.07,  7.04, 18.51,  8.14, 15.84,  7.89,
        5.23, 18.12,  8.57,  9.62, 12.91, 10.17,  8.55, 15.66,  9.36,
       16.14, 12.62,  7.12, 13.82, 15.88, 16.06,  5.5 , 17.84,  9.95,
       11.71, 12.23, 16.19, 18.26,  4.35, 17.25,  5.96,  8.95, 16.62,
       16.84, 11.69, 17.09, 14.9 , 13.48, 16.42,  4.96, 12.75, 14.15,
        6.87,  5.84,  9.23,  9.84, 13.88, 12.72, 10.24, 15.58, 11.68,
       10.47,  9.27,

In [44]:
sup = em > 18
conta = np.sum(sup)
media = np.mean(em[sup])

conta, media

(20, 18.964000000000002)

In [48]:
em_sup = np.sum(em[sup])
em_tot = np.sum(em)

fraz = em_sup/em_tot

em_sup, em_tot, fraz

(379.28000000000003, 2323.2799999999997, 0.16325195413381086)

## 7

In [50]:
survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12],
                           [40, 63000, 14], [29, 47000, 11], 
                           [35, 58000, 13] ])

In [52]:
ist_12 = survey_matrix[:,2] >= 12

sel = survey_matrix[ist_12]
sel

array([[   32, 52000,    12],
       [   40, 63000,    14],
       [   35, 58000,    13]])

In [53]:
sel[:,1]

array([52000, 63000, 58000])

In [54]:
np.mean(sel[:,1])

57666.666666666664

## 8

In [65]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59], dtype=float)

In [66]:
ages[ages==999] = np.nan

np.max(ages[~np.isnan(ages)])

112.0

## 9

In [67]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

In [68]:
len = len(lista_parole)

frase = f"""
"In epoche passate, viveva una donna saggia che era molto orgogliosa
dell'antico {lista_parole[np.random.randint(0, len)]} che proteggeva.
Quando un anziano del villaggio venne a chiederle consiglio su come garantire
al meglio un raccolto abbondante e le offrì il
{lista_parole[np.random.randint(0, len)]} come dono,
i suoi occhi si spalancarono e lei esclamò una sola parola,
\"{lista_parole[np.random.randint(0, len)]}\".

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta,
gli abitanti cercarono nella foresta un
{lista_parole[np.random.randint(0, len)]}.

Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano
cercando e tutti corsero dalla donna saggia per donarglielo.

Con un sorriso da un orecchio all’altro, e cantando canti di festa,
la donna saggia guardò i suoi compaesani e disse:
\"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza
{lista_parole[np.random.randint(0, len)]}!\" Ci fu grande gioia e celebrazione."
"""
print(frase)


"In epoche passate, viveva una donna saggia che era molto orgogliosa
dell'antico RECUPERO che proteggeva.
Quando un anziano del villaggio venne a chiederle consiglio su come garantire
al meglio un raccolto abbondante e le offrì il
PARENTE come dono,
i suoi occhi si spalancarono e lei esclamò una sola parola,
"INSEDIAMENTO".

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta,
gli abitanti cercarono nella foresta un
ALFABETIZZAZIONE.

Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano
cercando e tutti corsero dalla donna saggia per donarglielo.

Con un sorriso da un orecchio all’altro, e cantando canti di festa,
la donna saggia guardò i suoi compaesani e disse:
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza
VOLONTARIO!" Ci fu grande gioia e celebrazione."

